fix: fix piped curl output to sysout

diff --git a/eva b/eva
--- a/eva
+++ b/eva
@@ -47,32 +47,46 @@ mkdir -p "${MAMBA_ROOT_PREFIX}"
 log "MAMBA_ROOT_PREFIX: ${MAMBA_ROOT_PREFIX}"
 log "PATH: ${PATH}"
 
+ensure_basics() {
+    # ensure curl and procps are installed
+    to_install=()
+    if ! command_exists curl; then
+        to_install+=("curl")
+    fi
+    if ! command_exists ps; then
+        to_install+=("procps")
+    fi
+
+    if [ ${#to_install[@]} -eq 0 ]; then
+        return
+    fi
+
+    log "installing basic dependencies: ${to_install[*]}"
+
+    if command_exists apt-get; then
+        if [[ "$(id -u)" -eq 0 ]]; then
+            apt-get update && apt-get install -y "${to_install[@]}" && rm -rf /var/lib/apt/lists/*
+        else
+            sudo apt-get update && sudo apt-get install -y "${to_install[@]}" && sudo rm -rf /var/lib/apt/lists/*
+        fi
+    elif command_exists pacman; then
+        if [[ "$(id -u)" -eq 0 ]]; then
+            pacman -Sy --noconfirm "${to_install[@]}" && pacman -Scc --noconfirm
+        else
+            sudo pacman -Sy --noconfirm "${to_install[@]}" && sudo pacman -Scc --noconfirm
+        fi
+    else
+        log "Error: package manager not supported. Please install: ${to_install[*]}"
+        exit 1
+    fi
+}
+
 install_micromamba() {
     if [[ -x "${MAMBA_ROOT_PREFIX}/bin/micromamba" ]]; then
         return
     fi
 
     log "installing micromamba (silent)"
-
-    if ! command_exists curl; then
-        if command_exists apt-get; then
-            # if is root
-            if [[ "$(id -u)" -eq 0 ]]; then
-                apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
-            else
-                sudo apt-get update && sudo apt-get install -y curl && sudo rm -rf /var/lib/apt/lists/*
-            fi
-        elif command_exists pacman; then
-            if [[ "$(id -u)" -eq 0 ]]; then
-                pacman -Sy --noconfirm curl && pacman -Scc --noconfirm
-            else
-                sudo pacman -Sy --noconfirm curl && sudo pacman -Scc --noconfirm
-            fi
-        else
-            log "Error: curl is required to install micromamba"
-            exit 1
-        fi
-    fi
 
     BIN_FOLDER="${MAMBA_ROOT_PREFIX}/bin" \
         INIT_YES=no \
